# Bag of Words Model with Naive Bayes Classifier
Trained on hand-tagged data, tested on new comments?

In [ ]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Culminating Experience/HandTagged_for_GoogleColab.csv')
data.head()

### Label Encoding

This is a method to convert the class labels Positive, Negative, Neutral into numerical values that can be used by the model.

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data['Sentiment'] = le.fit_transform(data['Sentiment'])


### Cleaning the texts

In [ ]:
import re, nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, len(data['Sentiment'])):
  review = re.sub('[^a-zA-Z]', ' ', data['Comment'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  review = [ps.stem(word) for word in review if not word in set (stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


### Bag of Words model

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 3000)
X = cv.fit_transform(corpus).toarray()
y = data.iloc[:, 0].values

### Splitting into training and testing

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

### Naive Bayes Classifier

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

### Predicting Test Results

In [ ]:
y_pred = classifier.predict(X_test)

### Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 90  82 144]
 [ 25  40  62]
 [ 17  16 206]]


### Checking various metrics

In [ ]:
import numpy as np
np.shape(X_train)

(2727, 2171)

In [ ]:
accuracy_score(y_pred, y_test)

0.49266862170087977